### ISSUE TITLE
Should stakeOCEAN and unstakeOCEAN be private methods?

### ISSUE THREAD

**Issue by LinuxIsCool** [oceanprotocol/tokenspice2#1]
https://github.com/oceanprotocol/tokenspice2/blob/aeca439b4beb1462e1f988f5d8eac60c2c5e8cbf/agents/BaseAgent.py#L73

If my understanding of private methods and properties as denoted by starting with an underscore is correct, then it seems that on the base agent, staking and unstaking actions should be private methods.

The updated code would simply be:
```
def _stakeOCEAN(self, OCEAN_stake:float, pool:bpool.BPool):
        self._wallet.stakeOCEAN(OCEAN_stake, pool)

  def _unstakeOCEAN(self, BPT_unstake:float, pool:bpool.BPool):
      self._wallet.unstakeOCEAN(BPT_unstake, pool)
```

**Comment by trentmc** [comment]
This code is heavily WIP and it's very possible that stake and unstake will need to get called by external agents.
