### ISSUE TITLE
Valuation P/E and P/S should be unique.

### ISSUE THREAD

**Issue by LinuxIsCool** [oceanprotocol/tokenspice2#2]
https://github.com/oceanprotocol/tokenspice2/blob/aeca439b4beb1462e1f988f5d8eac60c2c5e8cbf/util/valuation.py#L28

These  functions are the same. I believe they should be slightly different given that one is P/E and  one is P/S. I don't know enough about KPI's to fix this confidently myself. Looking for help. 

```
def firmValuationPE(annual_revenue: float, p_e_ratio: float) -> float:
    """Valuation by price-to-earnings (P/E) ratio. Earnings are
    sales minus costs.
    Some people prefer P/E over P/S as it captures profitability. However, 
    companies plowing extra money into growth will have poor P/E. Eg Amazon.
    """
    return annual_revenue * p_e_ratio

def firmValuationPS(annual_revenue: float, p_e_ratio: float) -> float:
    """
    Valuation by price-to-sales (P/S) ratio.
    Valuation is simply a multiple of sales. 
    Datapoint: most blockchain co's are 30x-50x sales, as are high-flying 
    startups like Zoom.
    """
    return annual_revenue * p_e_ratio

```

**Comment by trentmc** [comment]
The price-to-sales one currently uses incorrect variable naming, it should be `p_s_ratio` not `p_e_ratio`. Just created #7 to address. Therefore *this* issue is obsolete.
