### ISSUE TITLE
Is BurnWallet Necessary? 

### ISSUE THREAD

**Issue by LinuxIsCool** [oceanprotocol/tokenspice2#4]
https://github.com/oceanprotocol/tokenspice2/blob/aeca439b4beb1462e1f988f5d8eac60c2c5e8cbf/agents/AgentWallet.py#L188

Is this class necessary given that there is an OCEANBurnerAgent? 

My static type checker raises on AgentWallet.transferUSD() since BurnWallet does not have the `depositUSD(amt)` method. Should it be implemented?

Maybe some clarification is required on this note:
```

class BurnWallet:
    """This is a wallet-level interface to send funds-to-burn to.
    This is *not* a burner wallet, that's a completely different concept.
    """

```

**Comment by trentmc** [comment]
> Is this class necessary given that there is an OCEANBurnerAgent?
Yes. We need a wallet-level interface to send funds-to-burn to.

> My static type checker raises on AgentWallet.transferUSD() since BurnWallet does not have the depositUSD(amt) method. Should it be implemented?
Yes.

> Maybe some clarification is required on this note ...
Sure, go for it with a PR.

**Comment by trentmc** [comment]
> My static type checker raises on AgentWallet.transferUSD() since BurnWallet does not have the depositUSD(amt) method. Should it be implemented?

> Yes

I just created #8 for this.
