### ISSUE TITLE
private_key type should be str not bool

### ISSUE THREAD

**Issue by LinuxIsCool** [oceanprotocol/tokenspice2#9]
https://github.com/oceanprotocol/tokenspice2/blob/81846f29ee92e0ad25b4cefb2bd9d1fbd1e151d0/agents/BaseAgent.py#L18

Not sure how this slipped through the type checking before, but it's tripping tests now. Simple fix, changed on LTF fork, but not worth a whole pull-request.

**Comment by trentmc** [comment]
Fixed as part of #17 in https://github.com/oceanprotocol/tokenspice2/commit/6f4e910a7224b9ac34d1a55d03ea3f2a532ca0c6
